name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.19.4 # Fixed Flutter version

dependencies:
  flutter:
    sdk: flutter
  bottom_sheet: ^4.0.2
  flutter_svg: ^2.0.10+1
  decimal: ^2.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/article.svg
    - assets/icons/local_mall.svg
    - assets/icons/person.svg
    - assets/icons/search.svg